# Deploy static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-lab4:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (lab4)
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'HTML AND CSS/lab4'

      - name: Deploy lab4 to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
